version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"
  postgres:
    image: postgres:9.5
    env_file:
      - .dbconfig
    expose:
      - 5432